export const Routes = {
  auth: {
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    forgotPassword: "/auth/forgot-password",
    verifyEmail: "/auth/verify-email",
  },
  public: {
    home: "/",
    terms: "/",
    notFound: "/404",
    explore: "/explore",
    wishlist: "/wishlist",
    emailVerificationSucess: '/auth/verify-email-success',
    exploreDetail: "/exploreDetail",
    meetings: "/meetings",
    meetingslist: "/meetingslist",
    contact: "/contact",
    blog: "/blog",
    blogDetail: "/blog-detail",
    createListing: {
      puppyListing: "/create-listing/puppy-listing",
      semenListing: "/create-listing/semen-listing",
      studListing: "/create-listing/stud-listing",
      futureListing: "/create-listing/future-listing",
      wantedPuppyListing: "/create-listing/wanted-puppy-listing",
      otherServicesListing: "/create-listing/other-services-listing",
    },
    userID: (userID: string) => `/user/${userID}`,
  },
  private: {
    dashboard: "/dashboard",
    account: "/account",
    meetings: "/account/meetings",
    profile: "/account/profile",
    addListing: '/add-listing',
    inbox: '/account/inbox',
    listings: '/account/listings',
    startlisting: '/startlisting',
    startlistingform: '/startlistingform',
    reservations: '/account/reservations',
    accountSettings: '/account/settings',
    trips: '/trips',
    wishlist: '/wishlist',
  },
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    passwords: "/admin/passwords",
    settings: "/admin/settings",
  },
};
