export const Routes = {
  auth: {
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    forgotPassword: "/auth/forgot-password",
  },
  public: {
    home: "/",
    terms: "/",
    notFound: "/404",
    explore: "/explore",
    wishlist: "/wishlist",
    emailVerificationSucess: '/auth/verify-email-success',
    exploreDetail: "/exploreDetail",
    startlisting: "/startlisting",
    startlistingform: "/startlistingform",
    meetings: "/meetings",
    meetingslist: "/meetingslist",
    contact: "/contact",
    blog: "/blog",
    blogDetail: "/blog-detail",
    createListing: {
      puppyListing: "/create-listing/puppy-listing",
      semenListing: "/create-listing/semen-listing",
      studListing: "/create-listing/stud-listing",
      futureListing: "/create-listing/future-listing",
      wantedPuppyListing: "/create-listing/wanted-puppy-listing",
      otherServicesListing: "/create-listing/other-services-listing",
    },
    userID: (userID: string) => `/user/${userID}`,
  },
  private: {
    account: "/account",
    meetings: "/account/meetings",
    profile: "/account/profile",
    addListing: '/add-listing',
    dashboard: '/account',
    inbox: '/account/inbox',
    listings: '/account/listings',
    reservations: '/account/reservations',
    accountSettings: '/account/settings',
    trips: '/trips',
    wishlist: '/wishlist',
  },
};
