export const Routes = {
  auth: {
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    forgotPassword: "/auth/forgot-password",
    verifyEmail: "/auth/verify-email",
  },
  public: {
    home: "/",
    privacy: "/content/privacy-policy",
    terms: "/content/terms-conditions-of-use",
    faq: "/content/faq",
    shippingAndPayment: "/content/shipping-and-payment",
    partners: "/content/partners",
    notFound: "/404",
    explore: "/explore",
    wishlist: "/wishlist",
    emailVerificationSucess: '/auth/verify-email-success',
    exploreDetail: "/exploreDetail",
    meetings: "/meetings",
    meetingslist: "/meetingslist",
    contact: "/contact",
    blog: "/blog",
    blogDetail: "/blog-detail",
    createListing: {
      puppyListing: "/startlistingform?type=puppy_litter",
      puppyLitterListing: "/startlistingform?type=puppy_litter",
      semenListing: "/startlistingform?type=semen",
      studListing: "/startlistingform?type=stud",
      futureListing: "/startlistingform?type=future",
      wantedPuppyListing: "/startlistingform?type=wanted",
      otherServicesListing: "/startlistingform?type=services",
    },
    userID: (userID: string) => `/user/${userID}`,
  },
  private: {
    dashboard: "/dashboard",
    account: "/account",
    meetings: "/account/meetings",
    profile: "/account/profile",
    addListing: '/add-listing',
    inbox: '/account/inbox',
    listings: '/account/listings',
    subscriptions: '/account/subscriptions',
    startlisting: '/startlisting',
    startlistingform: '/startlistingform',
    reservations: '/account/reservations',
    accountSettings: '/account/settings',
    trips: '/trips',
    wishlist: '/wishlist',
  },
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    passwords: "/admin/passwords",
    settings: "/admin/settings",
  },
};
