name: NextJS AWS Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    # This ONLY affects the GitHub runner, not your EC2
    - name: Setup Node.js (Builder)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install & Build
      run: |
        npm ci
        npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Permanent Node.js setup check (run once on EC2)
          if ! command -v node &> /dev/null; then
            echo "Installing Node.js..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            source ~/.bashrc
            nvm install 20
            npm install -g pm2
          fi
          
          # Your deployment commands
          cd pups4sale/next-frontend
          git pull origin main
          npm ci --omit=dev
          pm2 restart frontend --update-env