name: Deploy Next.js to EC2 (via build branch)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install & Build
      run: |
        pnpm install --frozen-lockfile
        pnpm build

    - name: Prepare build branch
      run: |
        mkdir deploy && cp -r .next public package.json pnpm-lock.yaml next.config.js deploy/
        cd deploy
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git checkout -B build
        git add .
        git commit -m "Deploy: production build"
        git push --force origin build

    - name: Deploy to EC2 from build branch
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Setup Node and pnpm if not installed
          if ! command -v node &> /dev/null; then
            echo "Installing Node.js and pnpm..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            nvm install 20
            npm install -g pnpm pm2
          fi

          # Pull the latest from build branch and restart
          cd ~/pups4sale/next-frontend || mkdir -p ~/pups4sale/next-frontend && cd $_
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
            git checkout -b build
          fi
                     git fetch origin build
           git reset --hard origin/build
           
           # Set up environment
           export NVM_DIR="$HOME/.nvm"
           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
           
           pnpm install --prod
           pm2 start "pnpm start" --name frontend || pm2 restart frontend --update-env
